/* ============================================================================
   HabitCrafts — tools/precache.mjs
   WHAT THE SERVICE WORKER SHOULD KEEP.        node tools/precache.mjs

   Writes `prototype/sw-manifest.js`: the list of URLs to cache and a version
   string. Generated rather than hand-maintained, because a hand-maintained
   precache list is wrong the first time somebody adds a view and nobody finds
   out until they are underground with no signal.

   ---------------------------------------------------------------------------
   IT WALKS THE IMPORT GRAPH, IT DOES NOT GLOB THE DIRECTORY
   ---------------------------------------------------------------------------
   `prototype/` is 2.4MB. The app reaches about half of it: the other half is the
   reviewer harness, the design-system gallery, eleven legacy standalone pages,
   twenty unused logos and 73KB of build notes. Caching all of it would put a
   megabyte of things nobody opens on the phone.

   So this starts at `app.html` and follows what is actually reachable: the
   stylesheets and the module graph from `js/app.js` down. A file nobody imports
   is a file nobody needs offline, and it falls out for free.

   ---------------------------------------------------------------------------
   THE VERSION IS THE CONTENT, NOT THE CLOCK
   ---------------------------------------------------------------------------
   A timestamp would make every build a new cache even when nothing changed,
   which means a pointless re-download on a train. A hash of the file list and
   their sizes changes only when something actually did.
   ========================================================================= */

import { readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const app = resolve(root, 'prototype');

/* --------------------------------------------------------------------------
   THE WALK
-------------------------------------------------------------------------- */

const seen = new Set();

function add(rel) {
  const abs = resolve(app, rel);
  if (!existsSync(abs) || seen.has(rel)) return false;
  seen.add(rel);
  return true;
}

/** Every `import ... from '...'` and `import('...')` in one module. */
function importsOf(abs) {
  const src = readFileSync(abs, 'utf8');
  const out = [];
  const re = /(?:from|import)\s*\(?\s*['"](\.[^'"]+)['"]/g;
  let m;
  while ((m = re.exec(src))) out.push(m[1]);
  return out;
}

function walkModule(rel) {
  if (!add(rel)) return;
  const abs = resolve(app, rel);
  for (const spec of importsOf(abs)) {
    const next = relative(app, resolve(dirname(abs), spec)).split('\\').join('/');
    walkModule(next);
  }
}

/* The entry document, and what its <head> pulls in. Parsed rather than listed,
   so a fourth stylesheet is picked up without anybody remembering to. */
const entry = 'app.html';
add(entry);
const html = readFileSync(resolve(app, entry), 'utf8');
for (const m of html.matchAll(/(?:href|src)="([^"]+\.(?:css|js|png|webmanifest))"/g)) {
  if (!m[1].startsWith('http')) add(m[1]);
}

walkModule('js/app.js');

/* Views are loaded lazily by the router, so nothing imports them statically and
   the walk above cannot see them. Offline they are exactly what is wanted: a
   route that only works with signal is a route that fails on the train. */
const routes = readFileSync(resolve(app, 'js/router.js'), 'utf8');
for (const m of routes.matchAll(/import\('\.\/(views\/[^']+)'\)/g)) walkModule('js/' + m[1]);

/* Corpora, which are not imported by the router and are the actual content. */
const study = readFileSync(resolve(app, 'js/study.js'), 'utf8');
for (const m of study.matchAll(/from\s+'\.\/(corpus\/[^']+|data-japanese\.js)'/g)) {
  walkModule('js/' + m[1]);
}

add('manifest.webmanifest');
for (const i of ['icon-192', 'icon-512', 'icon-512-maskable', 'apple-touch-icon']) {
  add(`assets/icons/${i}.png`);
}

/* --------------------------------------------------------------------------
   THE OUTPUT
-------------------------------------------------------------------------- */

const files = [...seen].sort();
const hash = createHash('sha256');
let bytes = 0;
for (const f of files) {
  const size = statSync(resolve(app, f)).size;
  bytes += size;
  hash.update(`${f}:${size}\n`);
}
const version = hash.digest('hex').slice(0, 12);

writeFileSync(resolve(app, 'sw-manifest.js'), `/* GENERATED by tools/precache.mjs. Do not edit.
   ${files.length} files, ${(bytes / 1024).toFixed(0)}KB. Version is a hash of the
   list and their sizes, so it changes when the app does and not when the clock
   does: a timestamp would re-download everything on a train for nothing. */
export const VERSION = '${version}';
export const PRECACHE = ${JSON.stringify(files, null, 2)};
`, 'utf8');

console.log(`  ${files.length} files, ${(bytes / 1024).toFixed(0)}KB, version ${version}`);
const total = 2513868;
console.log(`  (prototype/ is ${(total / 1024).toFixed(0)}KB; ${(100 - (bytes / total) * 100).toFixed(0)}% of it is not cached)`);
