/* ============================================================================
   HabitCrafts — sw.js
   THE APP STILL OPENS UNDERGROUND.

   Cache-first over a precached list, which is the whole strategy and is enough
   because every file here is static and immutable per deploy. There is no API
   to be stale against: the corpora are code, and the only thing that changes
   while the app runs is localStorage, which a service worker never touches.

   The list and the version come from `sw-manifest.js`, generated by
   tools/precache.mjs. Hand-maintaining a precache list works until the first
   time somebody adds a view, and then it silently stops covering it and nobody
   finds out until they are on a train with no signal.

   ---------------------------------------------------------------------------
   NAVIGATION FALLS BACK TO app.html, AND THE ROUTER MAKES THAT FREE
   ---------------------------------------------------------------------------
   Routing is hash-based, so every route in the app is the same document with a
   different fragment. Offline, any navigation request can be answered with the
   cached `app.html` and the router sorts out the rest. An app with real paths
   would need a rule per route; this one needs a line.

   ---------------------------------------------------------------------------
   A VERSION BUMP THROWS THE OLD CACHE AWAY, ON ACTIVATE AND NOT BEFORE
   ---------------------------------------------------------------------------
   Deleting during `install` would pull files out from under the page that is
   still running on them. The old cache is deleted in `activate`, which only
   fires once the new worker has taken over.
   ========================================================================= */

import { VERSION, PRECACHE } from './sw-manifest.js';

const CACHE = `habitcrafts-ja-${VERSION}`;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* One at a time with a catch, not `cache.addAll()`. addAll is atomic: one
       404 among forty-six files rejects the whole install and the app silently
       has no offline support at all, with nothing in the UI to say so. A
       missing file should cost that file. */
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (res.ok) await cache.put(url, res);
      } catch (e) { /* one file, not the install */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('habitcrafts-ja-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;

  /* Only GET, and only our own origin. A POST is not cacheable and a
     cross-origin request is not ours to answer. */
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;

    try {
      const res = await fetch(request);
      /* Fill in anything reachable that the precache list missed, so the second
         visit to a screen works offline even if the first needed signal. */
      if (res.ok && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(request, res.clone());
      }
      return res;
    } catch (e) {
      /* Offline and not cached. Every route is the same document, so a
         navigation can always be answered. Anything else genuinely fails. */
      if (request.mode === 'navigate') {
        const shell = await caches.match('app.html', { ignoreSearch: true });
        if (shell) return shell;
      }
      throw e;
    }
  })());
});
